from dotenv import load_dotenv
load_dotenv() 

from agent.solver import run_agent
from agent.llm import llm_generate_tests


def interactive():
    
    print("=" * 60)
    print("  CP Agent — Interactive Mode")
    print("  Test cases are AUTO-GENERATED by AI!")
    print("=" * 60)

    print("\nPaste your problem (type END on a new line when done):\n")
    lines = []
    while True:
        line = input()
        if line.strip().upper() == "END":
            break
        lines.append(line)
    problem = "\n".join(lines).strip()

    if not problem:
        print("No problem entered. Exiting.")
        return

    tries = input("\nMax attempts? [default 3]: ").strip()
    max_attempts = int(tries) if tries.isdigit() else 3

    model = "llama-3.3-70b-versatile"

    
    test_cases = llm_generate_tests(problem, model)

    if not test_cases:
        print("Could not generate test cases. Exiting.")
        return

    
    run_agent(problem, test_cases, max_attempts=max_attempts, model=model)


if __name__ == "__main__":
    interactive()
